# Accidentes en tráfico en Zaragoza 

¿Qué vamos a hacer?

 * obtener los datos
 * transformar el campo coordenadas
 * construir un tabla con motivo del accidente, latitud y longitud

## Origen de datos


https://www.zaragoza.es/sede/servicio/catalogo/1500#API

El delimitador es el **;**
Tiene dos parámetros, rows y start

In [10]:
import pandas as pd
import folium

In [2]:
url = 'https://www.zaragoza.es/sede/servicio/transporte/accidentalidad-trafico/accidente.csv?rows=100'

In [13]:
archivo = "/Users/koli/Documents/ELISAVA/DATA/cbernadthomas-MGLG/accidentes.csv"

In [14]:
df = pd.read_csv(archivo,delimiter=',')

In [15]:
df

,id,year,type,accidentType,firstAddress,secondAddress,geometry,reason,area,creationDate,daniosMateriales,falloMecanico,estadoPavimento,tipoEstadoPavimento,estadoAtmosfera,tipoEstadoAtmosfera,afectado,vehiculo
0,https://www.zaragoza.es/sede/servicio/transpor...,2014,SALIDA CALZADA,NaN,"COSTA, JOAQUIN","PERAL, ISAAC","-0.8818527060979306,41.649027473051156",PERDIDA del control por FALTA de ATENCIÓN,NaN,2014-10-09T00:00:00Z,True,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,NaN,https://www.zaragoza.es/sede/servicio/transpor...
1,https://www.zaragoza.es/sede/servicio/transpor...,2014,COLISIÓN ALCANCE,NaN,CADENA(MARQUES DE LA),NaN,"-0.8645810716721081,41.661585829868585","DISTANCIA DE SEGURIDAD, no mantener",2560.0,2014-10-23T00:00:00Z,False,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,https://www.zaragoza.es/sede/servicio/transpor...,https://www.zaragoza.es/sede/servicio/transpor...
2,https://www.zaragoza.es/sede/servicio/transpor...,2014,COLISIÓN ALCANCE,NaN,"GOMEZ AVELLANEDA, G.","CASTRO, R. (POETA)","-0.887776415002892,41.666992622958105",PERDIDA del control por FALTA de ATENCIÓN,2598.0,2014-10-23T00:00:00Z,False,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,https://www.zaragoza.es/sede/servicio/transpor...,https://www.zaragoza.es/sede/servicio/transpor...
3,https://www.zaragoza.es/sede/servicio/transpor...,2014,COLIS FRONTOLATERAL,NaN,MONZON,"GARCIA CONDOY, H.","-0.8825260453930127,41.62957498750602","CEDA EL PASO, no respetar prioridad de paso",2555.0,2014-10-23T00:00:00Z,False,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,https://www.zaragoza.es/sede/servicio/transpor...,https://www.zaragoza.es/sede/servicio/transpor...
4,https://www.zaragoza.es/sede/servicio/transpor...,2014,SALIDA CALZADA,NaN,RIOJA,"NAVARRA, AVENIDA DE","-0.908314757720389,41.6562121210704",PERDIDA del control por VELOCIDAD INADECUADA,2554.0,2014-10-24T00:00:00Z,False,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,https://www.zaragoza.es/sede/servicio/transpor...,https://www.zaragoza.es/sede/servicio/transpor...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27495,https://www.zaragoza.es/sede/servicio/transpor...,2019,COLISIÓN LATERAL,NaN,"PLEYADES, LAS",BOYERO,"-0.9337782877014544,41.63888841722081",INCORPORARSE sin las debidas precauciones,2512.0,2019-09-20T00:00:00Z,False,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,https://www.zaragoza.es/sede/servicio/transpor...,https://www.zaragoza.es/sede/servicio/transpor...
27496,https://www.zaragoza.es/sede/servicio/transpor...,2019,COLISIÓN LATERAL,NaN,"UNIVERSITAS, VIA",NaN,"-0.9067375759951974,41.644789184898926",INCORPORARSE sin las debidas precauciones,2513.0,2019-09-18T00:00:00Z,True,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,NaN,https://www.zaragoza.es/sede/servicio/transpor...
27497,https://www.zaragoza.es/sede/servicio/transpor...,2019,COLISIÓN LATERAL,NaN,"CANOVAS, ANTONIO",NaN,"-0.8907497377774148,41.64811436227578",INVADIR otro carril en el mismo sentido de cir...,2707.0,2019-09-21T00:00:00Z,True,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,NaN,https://www.zaragoza.es/sede/servicio/transpor...
27498,https://www.zaragoza.es/sede/servicio/transpor...,2019,SALIDA CALZADA,NaN,"LEGAZ LACAMBRA, LUIS","GOMEZ AVELLANEDA, G.","-0.8908180267513072,41.676074625860785",PERDIDA del control por FALTA de ATENCIÓN,2572.0,2019-09-22T00:00:00Z,True,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,NaN,https://www.zaragoza.es/sede/servicio/transpor...
27499,https://www.zaragoza.es/sede/servicio/transpor...,2019,COLISIÓN LATERAL,NaN,"RODRIGUEZ AYUSO, MANUEL",BIEL,"-0.9245669583272559,41.645615385662296",INVADIR otro carril en el mismo sentido de cir...,2540.0,2019-09-20T00:00:00Z,False,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,https://www.zaragoza.es/sede/servicio/transpor...,https://www.zaragoza.es/sede/servicio/transpor...

Aquí tenemos todos los datos pero mejor si lo evitamos, son 27000 accidentes y puede ir lento.

In [17]:
#df = pd.read_csv('http://muimota.net/ojoaldato/accidentes.csv')
#df

In [18]:
df['reason'].unique()

<StringArray>
[                      'PERDIDA del control por FALTA de ATENCIÓN',
                             'DISTANCIA DE SEGURIDAD, no mantener',
                     'CEDA EL PASO, no respetar prioridad de paso',
                    'PERDIDA del control por VELOCIDAD INADECUADA',
                         'Caída de ocupante en Transporte Público',
                     'PEATÓN cruza calz SIN PREFER. fuera de paso',
          'INVADIR otro carril en el mismo sentido de circulación',
              'PEATÓN cruza calz SIN PREFER. en PASO CON semáforo',
                                  'PUERTA abierta incorrectamente',
                                                    'MARCHA ATRÁS',
                         'SEMÁFORO, no respetar prioridad de paso',
                                                    'OTRAS CAUSAS',
             'PEATÓN cruza calz CON PREFER. en PASO  CON semáforo',
             'PEATÓN cruza calz CON PREFER. en PASO  SIN semáforo',
              'PEATÓN cruza calz CON PREFER. en PASO SIN semáforo',
                       'INCORPORARSE sin las debidas precauciones',
            'GIROS: no respetar señal ó no ceñirse a la dirección',
              'PEATÓN cruza calz CON PREFER. en PASO CON semáforo',
                                 'Infracción Penal (con denuncia)',
                     'PEATÓN atropellado sobre la acera ó refugio',
             'PEATÓN cruza calz SIN PREFER. en PASO  CON semáforo',
                             'STOP, no respetar prioridad de paso',
                             'SIN PODER DETERMINAR,  faltan datos',
       'INVADIR otro carril en sentido contrario a la circulación',
                            'PREFERENCIA EN GLORIETA, no respetar',
           'PEATÓN cruza calz CON PREFER. fuera de PASO (esquina)',
                                'DIRECCIÓN CONTRARIA, circular en',
                              'SIN PODER DETERMINAR, faltan datos',
                                     'ESTACIONADO INCORRECTAMENTE',
                          'PREFERENCIA A LA  DERECHA, no respetar',
                           'PREFERENCIA A LA DERECHA, no respetar',
                                       'ADELANTAMIENTO incorrecto',
                                                 'Daños propiedad',
                                                    'Otras causas',
 'INCORPORARSE un BUS URBANO a la circulac. desde parada señaliz.',
                                      'CAIDA DE PEATÓN EN AUTOBUS',
                                               'Daños (Propiedad)',
                                                               nan,
                      'INCORPORARSE sin las debidas precauciones)',
                      'PEATÓN cruza calz  fuera de PASO (esquina)',
                                 'Infracción Penal (sin denuncia)']
Length: 41, dtype: str

In [19]:
df = df.sample(200).reset_index(drop=True)
df

,id,year,type,accidentType,firstAddress,secondAddress,geometry,reason,area,creationDate,daniosMateriales,falloMecanico,estadoPavimento,tipoEstadoPavimento,estadoAtmosfera,tipoEstadoAtmosfera,afectado,vehiculo
0,https://www.zaragoza.es/sede/servicio/transpor...,2016,COLISIÓN LATERAL,NaN,"MOZART,PL W.AMADEO",CADENA(MARQUES DE LA),"-0.8649768285622407,41.661979621113716",INVADIR otro carril en el mismo sentido de cir...,2272.0,2016-08-17T00:00:00Z,True,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,NaN,https://www.zaragoza.es/sede/servicio/transpor...
1,https://www.zaragoza.es/sede/servicio/transpor...,2016,COLISIÓN ALCANCE,NaN,"ISABEL CATOLICA, PS.",NaN,"-0.9002814025323488,41.636588081212594",PERDIDA del control por FALTA de ATENCIÓN,1772.0,2016-06-22T00:00:00Z,True,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,NaN,https://www.zaragoza.es/sede/servicio/transpor...
2,https://www.zaragoza.es/sede/servicio/transpor...,2015,CAIDA SOBRE CALZADA,NaN,"CONSTITUCION, PASEO","PERAL, ISAAC","-0.8820699189930906,41.648371333350916",PERDIDA del control por FALTA de ATENCIÓN,833.0,2015-03-12T00:00:00Z,False,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,https://www.zaragoza.es/sede/servicio/transpor...,https://www.zaragoza.es/sede/servicio/transpor...
3,https://www.zaragoza.es/sede/servicio/transpor...,2014,COLISIÓN ALCANCE,NaN,SAN LORENZO,"SAN PEDRO NOLASCO, PL","-0.8765982776515893,41.65279159686066",PERDIDA del control por FALTA de ATENCIÓN,NaN,2014-12-29T00:00:00Z,True,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,NaN,NaN
4,https://www.zaragoza.es/sede/servicio/transpor...,2018,ATROPELLO,NaN,BIELSA,"CHIMENEAS, LAS","-0.8691726895974136,41.66210902263132",PEATÓN cruza calz CON PREFER. en PASO SIN sem...,3416.0,2018-12-21T00:00:00Z,False,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,https://www.zaragoza.es/sede/servicio/transpor...,https://www.zaragoza.es/sede/servicio/transpor...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,https://www.zaragoza.es/sede/servicio/transpor...,2011,COLISIÓN LATERAL,NaN,"CASPE, AV.COMPROMISO",NaN,"-0.861263025065956,41.64517934808708",INVADIR otro carril en el mismo sentido de cir...,3858.0,2011-08-24T00:00:00Z,False,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,https://www.zaragoza.es/sede/servicio/transpor...,https://www.zaragoza.es/sede/servicio/transpor...
196,https://www.zaragoza.es/sede/servicio/transpor...,2015,COLISIÓN ALCANCE,NaN,"NAVARRA, AVENIDA DE",NaN,"-0.9072251064166048,41.655364741653315",INVADIR otro carril en el mismo sentido de cir...,2345.0,2015-09-21T00:00:00Z,True,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,NaN,https://www.zaragoza.es/sede/servicio/transpor...
197,https://www.zaragoza.es/sede/servicio/transpor...,2012,COLISIÓN LATERAL,NaN,JUAN CARLOS I BORBON,NaN,"-0.908898617351804,41.63971658007118",PERDIDA del control por FALTA de ATENCIÓN,3269.0,2012-07-26T00:00:00Z,True,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,NaN,https://www.zaragoza.es/sede/servicio/transpor...
198,https://www.zaragoza.es/sede/servicio/transpor...,2015,OTRAS,NaN,CADENA(MARQUES DE LA),"JOTA, AVENIDA DE LA","-0.8630518454272499,41.660236381478796",OTRAS CAUSAS,1939.0,2015-07-13T00:00:00Z,True,False,MAL ESTADO,NaN,BUEN ESTADO,NaN,NaN,https://www.zaragoza.es/sede/servicio/transpor...
199,https://www.zaragoza.es/sede/servicio/transpor...,2015,COLIS FRONTOLATERAL,NaN,"MADRID, AVENIDA DE",SAN PASCUAL BAILON,"-0.9160054982404382,41.65079146239229","SEMÁFORO, no respetar prioridad de paso",259.0,2015-01-19T00:00:00Z,False,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,https://www.zaragoza.es/sede/servicio/transpor...,https://www.zaragoza.es/sede/servicio/transpor...

# Coordenadas

In [20]:
df['geometry']

0      -0.8649768285622407,41.661979621113716
1      -0.9002814025323488,41.636588081212594
2      -0.8820699189930906,41.648371333350916
3       -0.8765982776515893,41.65279159686066
4       -0.8691726895974136,41.66210902263132
                        ...
195      -0.861263025065956,41.64517934808708
196    -0.9072251064166048,41.655364741653315
197      -0.908898617351804,41.63971658007118
198    -0.8630518454272499,41.660236381478796
199     -0.9160054982404382,41.65079146239229
Name: geometry, Length: 200, dtype: str

### Convertir una cadena a dos coordenadas

guardado en cadena, con esto no se puede hacer el mapa, tenemos que 'parsear' a latitud y longitud

In [21]:
df['geometry']

0      -0.8649768285622407,41.661979621113716
1      -0.9002814025323488,41.636588081212594
2      -0.8820699189930906,41.648371333350916
3       -0.8765982776515893,41.65279159686066
4       -0.8691726895974136,41.66210902263132
                        ...
195      -0.861263025065956,41.64517934808708
196    -0.9072251064166048,41.655364741653315
197      -0.908898617351804,41.63971658007118
198    -0.8630518454272499,41.660236381478796
199     -0.9160054982404382,41.65079146239229
Name: geometry, Length: 200, dtype: str

In [22]:
df['geometry'][0]

'-0.8649768285622407,41.661979621113716'

In [23]:
df['geometry'][0].split(',')

['-0.8649768285622407', '41.661979621113716']

In [24]:
'1' + '2'

'12'

In [25]:
float('12')

12.0

In [26]:
pointStr = df['geometry'][0].split(',')

In [27]:
pointStr

['-0.8649768285622407', '41.661979621113716']

In [28]:
pointStr[0]

'-0.8649768285622407'

In [29]:
float(pointStr[0])

-0.8649768285622407

In [30]:
[float(pointStr[0]),float(pointStr[1])]

[-0.8649768285622407, 41.661979621113716]

## Longitud y Latitud
Vamos a hacer dos listas una de longitudes y otra de latitudes
Explicar:
 * bucles
 * añadir a lista

In [31]:
df['geometry']

0      -0.8649768285622407,41.661979621113716
1      -0.9002814025323488,41.636588081212594
2      -0.8820699189930906,41.648371333350916
3       -0.8765982776515893,41.65279159686066
4       -0.8691726895974136,41.66210902263132
                        ...
195      -0.861263025065956,41.64517934808708
196    -0.9072251064166048,41.655364741653315
197      -0.908898617351804,41.63971658007118
198    -0.8630518454272499,41.660236381478796
199     -0.9160054982404382,41.65079146239229
Name: geometry, Length: 200, dtype: str

In [32]:
l = []
l = l + [1,2]
l = l + [3]
l

[1, 2, 3]

In [33]:
longitudes = []
for coordenadasStr in df['geometry']:
    pointStr = coordenadasStr.split(',')
    longitudes += [float(pointStr[0])]

In [34]:
latitudes = []
for coordenadasStr in df['geometry']:
    pointStr = coordenadasStr.split(',')
    latitudes += [float(pointStr[1])]

In [35]:
coordenadas = pd.DataFrame({'long':longitudes,'lat':latitudes})
coordenadas

         long        lat
0   -0.864977  41.661980
1   -0.900281  41.636588
2   -0.882070  41.648371
3   -0.876598  41.652792
4   -0.869173  41.662109
..        ...        ...
195 -0.861263  41.645179
196 -0.907225  41.655365
197 -0.908899  41.639717
198 -0.863052  41.660236
199 -0.916005  41.650791

[200 rows x 2 columns]

In [36]:
df

,id,year,type,accidentType,firstAddress,secondAddress,geometry,reason,area,creationDate,daniosMateriales,falloMecanico,estadoPavimento,tipoEstadoPavimento,estadoAtmosfera,tipoEstadoAtmosfera,afectado,vehiculo
0,https://www.zaragoza.es/sede/servicio/transpor...,2016,COLISIÓN LATERAL,NaN,"MOZART,PL W.AMADEO",CADENA(MARQUES DE LA),"-0.8649768285622407,41.661979621113716",INVADIR otro carril en el mismo sentido de cir...,2272.0,2016-08-17T00:00:00Z,True,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,NaN,https://www.zaragoza.es/sede/servicio/transpor...
1,https://www.zaragoza.es/sede/servicio/transpor...,2016,COLISIÓN ALCANCE,NaN,"ISABEL CATOLICA, PS.",NaN,"-0.9002814025323488,41.636588081212594",PERDIDA del control por FALTA de ATENCIÓN,1772.0,2016-06-22T00:00:00Z,True,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,NaN,https://www.zaragoza.es/sede/servicio/transpor...
2,https://www.zaragoza.es/sede/servicio/transpor...,2015,CAIDA SOBRE CALZADA,NaN,"CONSTITUCION, PASEO","PERAL, ISAAC","-0.8820699189930906,41.648371333350916",PERDIDA del control por FALTA de ATENCIÓN,833.0,2015-03-12T00:00:00Z,False,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,https://www.zaragoza.es/sede/servicio/transpor...,https://www.zaragoza.es/sede/servicio/transpor...
3,https://www.zaragoza.es/sede/servicio/transpor...,2014,COLISIÓN ALCANCE,NaN,SAN LORENZO,"SAN PEDRO NOLASCO, PL","-0.8765982776515893,41.65279159686066",PERDIDA del control por FALTA de ATENCIÓN,NaN,2014-12-29T00:00:00Z,True,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,NaN,NaN
4,https://www.zaragoza.es/sede/servicio/transpor...,2018,ATROPELLO,NaN,BIELSA,"CHIMENEAS, LAS","-0.8691726895974136,41.66210902263132",PEATÓN cruza calz CON PREFER. en PASO SIN sem...,3416.0,2018-12-21T00:00:00Z,False,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,https://www.zaragoza.es/sede/servicio/transpor...,https://www.zaragoza.es/sede/servicio/transpor...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,https://www.zaragoza.es/sede/servicio/transpor...,2011,COLISIÓN LATERAL,NaN,"CASPE, AV.COMPROMISO",NaN,"-0.861263025065956,41.64517934808708",INVADIR otro carril en el mismo sentido de cir...,3858.0,2011-08-24T00:00:00Z,False,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,https://www.zaragoza.es/sede/servicio/transpor...,https://www.zaragoza.es/sede/servicio/transpor...
196,https://www.zaragoza.es/sede/servicio/transpor...,2015,COLISIÓN ALCANCE,NaN,"NAVARRA, AVENIDA DE",NaN,"-0.9072251064166048,41.655364741653315",INVADIR otro carril en el mismo sentido de cir...,2345.0,2015-09-21T00:00:00Z,True,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,NaN,https://www.zaragoza.es/sede/servicio/transpor...
197,https://www.zaragoza.es/sede/servicio/transpor...,2012,COLISIÓN LATERAL,NaN,JUAN CARLOS I BORBON,NaN,"-0.908898617351804,41.63971658007118",PERDIDA del control por FALTA de ATENCIÓN,3269.0,2012-07-26T00:00:00Z,True,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,NaN,https://www.zaragoza.es/sede/servicio/transpor...
198,https://www.zaragoza.es/sede/servicio/transpor...,2015,OTRAS,NaN,CADENA(MARQUES DE LA),"JOTA, AVENIDA DE LA","-0.8630518454272499,41.660236381478796",OTRAS CAUSAS,1939.0,2015-07-13T00:00:00Z,True,False,MAL ESTADO,NaN,BUEN ESTADO,NaN,NaN,https://www.zaragoza.es/sede/servicio/transpor...
199,https://www.zaragoza.es/sede/servicio/transpor...,2015,COLIS FRONTOLATERAL,NaN,"MADRID, AVENIDA DE",SAN PASCUAL BAILON,"-0.9160054982404382,41.65079146239229","SEMÁFORO, no respetar prioridad de paso",259.0,2015-01-19T00:00:00Z,False,False,BUEN ESTADO,NaN,BUEN ESTADO,NaN,https://www.zaragoza.es/sede/servicio/transpor...,https://www.zaragoza.es/sede/servicio/transpor...

In [37]:
latitudes[:10]

[41.661979621113716,
 41.636588081212594,
 41.648371333350916,
 41.65279159686066,
 41.66210902263132,
 41.64099414535668,
 41.64472747682678,
 41.65064625260204,
 41.65013288843604,
 41.64963422246641]

En este punto tenemos dos listas, una con las longitudes, otra con las latitudes. 
Vamos a construir un DataFrame con estos datos 
 * vamos a usar el indice para poder relacionar, concatenar las tablas

In [38]:
pd.DataFrame({'col1':[1,2,3],'col2':[4,5,6]})

   col1  col2
0     1     4
1     2     5
2     3     6

Creamos una tabla con el tipo longitud y latitud

In [39]:
df['type']

0         COLISIÓN LATERAL
1         COLISIÓN ALCANCE
2      CAIDA SOBRE CALZADA
3         COLISIÓN ALCANCE
4                ATROPELLO
              ...
195       COLISIÓN LATERAL
196       COLISIÓN ALCANCE
197       COLISIÓN LATERAL
198                  OTRAS
199    COLIS FRONTOLATERAL
Name: type, Length: 200, dtype: str

In [40]:
accidentes = pd.concat([df['type'],coordenadas],axis=1)

In [41]:
accidentes

                    type      long        lat
0       COLISIÓN LATERAL -0.864977  41.661980
1       COLISIÓN ALCANCE -0.900281  41.636588
2    CAIDA SOBRE CALZADA -0.882070  41.648371
3       COLISIÓN ALCANCE -0.876598  41.652792
4              ATROPELLO -0.869173  41.662109
..                   ...       ...        ...
195     COLISIÓN LATERAL -0.861263  41.645179
196     COLISIÓN ALCANCE -0.907225  41.655365
197     COLISIÓN LATERAL -0.908899  41.639717
198                OTRAS -0.863052  41.660236
199  COLIS FRONTOLATERAL -0.916005  41.650791

[200 rows x 3 columns]

En este punto queremos 'concatenar' la tabla con el motivo y las coordenadas. 
De manera parecida a los graficos del otro día

In [42]:
accidentes

                    type      long        lat
0       COLISIÓN LATERAL -0.864977  41.661980
1       COLISIÓN ALCANCE -0.900281  41.636588
2    CAIDA SOBRE CALZADA -0.882070  41.648371
3       COLISIÓN ALCANCE -0.876598  41.652792
4              ATROPELLO -0.869173  41.662109
..                   ...       ...        ...
195     COLISIÓN LATERAL -0.861263  41.645179
196     COLISIÓN ALCANCE -0.907225  41.655365
197     COLISIÓN LATERAL -0.908899  41.639717
198                OTRAS -0.863052  41.660236
199  COLIS FRONTOLATERAL -0.916005  41.650791

[200 rows x 3 columns]

accidentes.assign(lat=latitudes)

accidentes

accidentes['long'] = longitudes

accidentes

# Crear el Mapa

In [43]:
mapa = folium.Map(location=[41.64,-0.88])

In [44]:
mapa

In [45]:
mapa = folium.Map(location=[41.64,-0.88])

In [46]:
marcador = folium.Marker([41.64,-0.88], popup="Zaragoza")

In [47]:
mapa = mapa.add_child(marcador)

In [48]:
mapa

# construir un mapa interactivo a partir de la tabla

In [49]:
mapa = folium.Map(location=[41.649693,-0.887712])

In [50]:
for indice, fila in accidentes.iterrows():
    marcador = folium.Marker([fila['lat'],fila['long']],\
                             popup=fila['type'])
    mapa.add_child(marcador)

In [51]:
mapa

In [52]:
mapa.save("accidentes.html")

In [53]:
accidentes

                    type      long        lat
0       COLISIÓN LATERAL -0.864977  41.661980
1       COLISIÓN ALCANCE -0.900281  41.636588
2    CAIDA SOBRE CALZADA -0.882070  41.648371
3       COLISIÓN ALCANCE -0.876598  41.652792
4              ATROPELLO -0.869173  41.662109
..                   ...       ...        ...
195     COLISIÓN LATERAL -0.861263  41.645179
196     COLISIÓN ALCANCE -0.907225  41.655365
197     COLISIÓN LATERAL -0.908899  41.639717
198                OTRAS -0.863052  41.660236
199  COLIS FRONTOLATERAL -0.916005  41.650791

[200 rows x 3 columns]

In [61]:
for indice, fila in accidentes.iterrows():
pass

IndentationError: expected an indented block after 'for' statement on line 1 (4048233544.py, line 2)

In [62]:
m = folium.Map()

In [57]:
m

In [58]:
m = folium.Map(location=[41.649693,-0.887712], tiles="Stamen Terrain")

ValueError: Custom tiles must have an attribution.

In [59]:
m

In [ ]:
marcador = folium.Marker(location=[41.649693,-0.887712],icon=folium.Icon(color="red"))

In [ ]:
m.add_child(marcador)

In [ ]:
m.save("index.html")